# Generated by Django 3.0.2 on 2020-01-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200110_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsquareuser',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Branch'),
        ),
    ]
