# Generated by Django 3.0.2 on 2020-01-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200111_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.CharField(default='Days', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='installment_duration_type',
            field=models.CharField(default='Days', max_length=20),
            preserve_default=False,
        ),
    ]
