# Generated by Django 3.0.2 on 2020-01-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='website.Subject'),
        ),
    ]
