# Generated by Django 3.0.2 on 2020-01-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200116_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='academic_year',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
