# Generated by Django 3.0.2 on 2020-01-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_batch_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_course_based',
            field=models.BooleanField(default=False),
        ),
    ]
