# Generated by Django 3.0.2 on 2020-01-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_batch_is_course_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsquareuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
