# Generated by Django 3.0.2 on 2020-01-21 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200118_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('discount', models.PositiveIntegerField()),
                ('discount_type', models.CharField(choices=[('FLT', 'Flat'), ('PER', 'Percentage')], max_length=4)),
                ('notes', models.CharField(max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled', to='website.StudentProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.StudentCourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('academic_year', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Course')),
                ('student_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='website.StudentCourse')),
            ],
        ),
    ]
